import { ConfigProvider } from 'antd';
import 'antd/es/style';
import enUS from 'antd/locale/en_US';
import type { Metadata } from 'next';
import './globals.css';
import AppLayout from './layout/layout';
import styles from './layout/layout.module.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ConfigProvider locale={enUS}>
				<body className={styles.body}>
					<AppLayout>{children}</AppLayout>
				</body>
			</ConfigProvider>
		</html>
	);
}
